/** IoC symbols for repositories (DIP). */
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const STUDENT_REPOSITORY = Symbol('STUDENT_REPOSITORY');
export const ASSISTANT_REPOSITORY = Symbol('ASSISTANT_REPOSITORY');
export const SECTION_REPOSITORY = Symbol('SECTION_REPOSITORY');
export const GROUP_REPOSITORY = Symbol('GROUP_REPOSITORY');
export const ASSISTANTSHIP_REPOSITORY = Symbol('ASSISTANTSHIP_REPOSITORY');
export const ATTENDANCE_CHECK_REPOSITORY = Symbol('ATTENDANCE_CHECK_REPOSITORY');
